# Generated by Django 5.2.6 on 2026-02-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_text_question_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='total_questions',
        ),
    ]
