# Generated by Django 5.2.6 on 2026-02-07 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_lesson_total_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionattempt',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='userquestionattempt',
            name='selected_answer',
        ),
        migrations.AlterField(
            model_name='userquestionattempt',
            name='confidence_rate',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
