# Generated by Django 5.2.6 on 2026-02-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userquestionattempt_is_correct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
