# Generated by Django 5.2.6 on 2026-02-10 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('mid-level', 'Mid-Level'), ('senior', 'Senior')], default='beginner', max_length=20)),
                ('known_technologies', models.TextField(blank=True, help_text='Comma-separated list of technologies')),
                ('learning_technologies', models.TextField(blank=True, help_text='Comma-separated list of technologies to learn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
